import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import { workbookFixture } from "./spreadsheet-fixture";
import { classReturnPath } from "../modules/users/return-path";
import { csvTemplate, previewCSV, tableToCSV } from "../modules/users/csv";

test("CSV: preserve leading zero, escaped quotes, BOM and semicolon; reject duplicates", () => {
  const source = '\uFEFFlogin_id;full_name;email;role;password;nis\r\n001;"Siswa, ""Satu""";one@example.test;student;TestOnly123!;00001';
  const rows = previewCSV(source);
  expect(rows[0].user.full_name).toBe('Siswa, "Satu"');
  expect(rows[0].user.nis).toBe("00001");
  expect(rows[0].errors).toEqual([]);
  expect(previewCSV(source + '\r\n001;Dua;two@example.test;student;TestOnly123!;00001').every(r => r.errors.length > 0)).toBe(true);
  expect(() => previewCSV('login_id,full_name,email,role,password\n"broken')).toThrow();
  expect(() => previewCSV(csvTemplate)).toThrow();
});

test("Excel paste: Indonesian columns, optional email, dates and passwords remain valid", () => {
  const header = "ID pengguna\tNama lengkap\tPeran\tKata sandi\tTanggal lahir\tNomor HP";
  const rows = previewCSV(header + '\n001\tGuru A\tGuru\t TestOnly123! \t29/02/2000\t081234567890');
  expect(rows[0].errors).toEqual([]);
  expect(rows[0].user).toMatchObject({ login_id: "001", role: "teacher", email: "", birth_date: "2000-02-29", password: " TestOnly123! " });
  expect(previewCSV(header + '\n001\tGuru A\tGuru\tTestOnly123!\t29/02/2001\twrong')[0].errors).toHaveLength(2);
  expect(previewCSV(tableToCSV([["ID pengguna", "Nama lengkap", "Peran", "Kata sandi"], ["001", "Guru, A", "Guru", "TestOnly123!"]]))[0].errors).toEqual([]);
  expect(() => previewCSV(header + Array.from({length: 51}, (_,i) => `\n${i}\tGuru\tGuru\tTestOnly123!\t\t`).join(""))).toThrow(/1–50/);
  expect(() => previewCSV("ID pengguna\tlogin_id\tNama lengkap\tPeran\tKata sandi\n1\t1\tGuru\tGuru\tTestOnly123!")).toThrow(/judul kolom/);
});

test("profile return destination only accepts class member tabs", () => {
  expect(classReturnPath("/kelas/42?tab=siswa")).toBe("/kelas/42?tab=siswa");
  expect(classReturnPath("/kelas/42?tab=guru")).toBe("/kelas/42?tab=guru");
  for (const value of [undefined, ["/kelas/42?tab=siswa"], "https://example.com", "//example.com", "/kelas/0?tab=siswa", "/kelas/42?tab=siswa\n", "/kelas/42?tab=unknown", "/kelas/42?tab=guru&redirect=https://example.com", "/kelas/9007199254740992?tab=siswa"]) expect(classReturnPath(value)).toBeNull();
});

test.describe("admin management writes (opt-in, temporary local fixtures)", () => {
  test.skip(process.env.E2E_MANAGEMENT !== "1", "Set E2E_MANAGEMENT=1 with local API/MySQL running.");
  const tag = "E2E" + randomBytes(10).toString("hex");
  test.afterAll(() => {
    if (process.env.E2E_MANAGEMENT !== "1") return;
    const backend = resolve(process.cwd(), "../LMS_12PPLG2_BE");
    execFileSync("go", ["run", "./cmd/e2e-cleanup", "--tag", tag], { cwd: backend, env: { ...process.env, GOCACHE: resolve(backend, ".local/go-cache") }, timeout: 60_000, stdio: "pipe" });
  });
  test("create/edit users, atomic import, class members/teachers, announcements and mobile", async ({ page }) => {
    test.setTimeout(180_000);
    page.setDefaultTimeout(15_000);
    await page.goto("/login");
    await page.getByLabel(/^ID pengguna(?: \*)?$/).fill(process.env.E2E_ADMIN_ID || "ADMIN001");
    await page.getByLabel(/^Kata sandi(?: \*)?$/).fill(process.env.E2E_ADMIN_PASSWORD || "Admin123!");
    await page.getByRole("button", { name: "Masuk ke portal" }).click();
    await expect(page).toHaveURL(/\/dashboard$/);
    const nav = page.getByRole("navigation", { name: "Navigasi utama" });
    await expect(nav.getByRole("link", { name: /Asesmen|Tugas|Assignment/i })).toHaveCount(0);
    await page.goto("/asesmen"); await expect(page).toHaveURL(/\/kelas$/);
    await page.goto("/pengguna/baru");
    await page.getByLabel("Isi ID pengguna sendiri").check();
    await page.getByLabel(/^Nama lengkap(?: \*)?$/).fill(tag + "-Siswa");
    await page.getByLabel(/^ID pengguna(?: \*)?$/).fill(tag + "-student");
    await page.getByLabel("Tempat lahir", { exact: true }).fill("Depok");
    await page.getByLabel("Tanggal lahir", { exact: true }).fill("2008-02-29");
    await page.getByLabel("Nomor HP", { exact: true }).fill("081234567890");
    await page.getByLabel(/^NIS(?: \*)?$/).fill(tag + "-nis");
    await page.getByLabel(/^Kata sandi awal(?: \*)?$/).fill("TestOnly123!");
    await page.getByRole("button", { name: "Buat akun", exact: true }).click();
    await expect(page.getByRole("status")).toContainText("Data pengguna berhasil disimpan");
    const userURL = page.url().split("?")[0];
    await page.reload();
    await expect(page.getByLabel("Tanggal lahir", { exact: true })).toHaveValue("2008-02-29");
    await expect(page.getByLabel("Alamat email", { exact: true })).toHaveValue("");
    await expect(page.locator(".topbar")).not.toContainText("SMK Citra Negara");
    await page.getByLabel(/^Nama lengkap(?: \*)?$/).fill(tag + "-Siswa Edit");
    await page.getByRole("button", { name: "Simpan perubahan", exact: true }).click();
    await expect(page.getByLabel(/^Nama lengkap(?: \*)?$/)).toHaveValue(tag + "-Siswa Edit");
    await page.getByRole("button", { name: "Ubah status " + tag + "-Siswa Edit" }).click();
    await page.getByLabel("Status baru").selectOption("inactive");
    await page.getByRole("button", { name: "Konfirmasi status" }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toContainText("berhasil");
    await page.getByRole("button", { name: "Tutup dialog" }).click();
    await page.getByRole("button", { name: "Ubah status " + tag + "-Siswa Edit" }).click();
    await page.getByLabel("Status baru").selectOption("active");
    await page.getByRole("button", { name: "Konfirmasi status" }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toContainText("berhasil");
    await page.getByRole("button", { name: "Tutup dialog" }).click();

    await page.goto("/pengguna/import");
    const csv = csvTemplate + `${tag}-teacher,${tag}-Guru,${tag}-teacher@example.test,teacher,TestOnly123!,,,,,,,\r\n`;
    await page.getByLabel("Berkas Excel atau CSV").setInputFiles({ name: "users.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: workbookFixture(tag + "-teacher", tag + "-Guru") });
    await page.getByLabel("Sheet Excel").selectOption({label:"Guru"});
    await page.getByRole("button", {name:"Pratinjau sheet"}).click();
    await expect(page.getByRole("cell", {name:/2000-02-29/})).toBeVisible();
    await expect(page.getByRole("cell", {name:/NIP: 000123/})).toBeVisible();
    await expect(page.getByRole("cell", { name: tag + "-Guru", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Simpan 1 pengguna" }).click();
    await expect(page.getByRole("status")).toContainText("1 pengguna berhasil diimport");
    await page.goto("/pengguna/import");
    await page.getByLabel("Tabel dari Excel").fill("ID pengguna\tNama lengkap\tPeran\tKata sandi\n" + tag + "-paste\tTempel Guru\tGuru\tTestOnly123!");
    await page.getByRole("button", {name:"Pratinjau tabel"}).click();
    await page.getByRole("button", {name:"Simpan 1 pengguna"}).click();
    await expect(page.getByRole("status")).toContainText("1 pengguna berhasil diimport");
    // Duplicate edits return feedback while retaining the user's unsaved fields.
    await page.goto(userURL);
    await page.getByLabel(/^ID pengguna(?: \*)?$/).fill(tag + "-teacher");
    await page.getByRole("button", { name: "Simpan perubahan", exact: true }).click();
    await expect(page.getByRole("alert").filter({ hasText: "sudah digunakan" })).toBeVisible();
    await expect(page.getByLabel(/^ID pengguna(?: \*)?$/)).toHaveValue(tag + "-teacher");
    // The second row conflicts with an existing account. No first-row user may remain.
    await page.goto("/pengguna/import");
    const conflict = csvTemplate + `${tag}-rollback,Rollback,${tag}-rollback@example.test,teacher,TestOnly123!,,,,,,,\r\n` + csv.slice(csvTemplate.length);
    await page.getByLabel("Berkas Excel atau CSV").setInputFiles({ name: "conflict.csv", mimeType: "text/csv", buffer: Buffer.from(conflict) });
    await page.getByRole("button", { name: "Simpan 2 pengguna" }).click();
    await expect(page.getByRole("alert").filter({ hasText: "sudah digunakan" })).toBeVisible();
    await page.goto("/pengguna"); await page.getByLabel("Cari pengguna").fill(tag + "-rollback");
    await expect(page.getByRole("heading", { name: "Tidak ada pengguna yang sesuai" })).toBeVisible();

    await page.goto("/kelas/baru");
    await page.getByLabel(/^Nama kelas(?: \*)?$/).fill(tag + "-Kelas");
    await page.getByLabel(/^Jurusan(?: \*)?$/).selectOption({index:1});
    await page.getByLabel(/^Nama ruang(?: \*)?$/).fill("Ruang uji");
    await page.getByLabel(/^Deskripsi kelas(?: \*)?$/).fill("Kelas sementara untuk pengujian browser.");
    await page.getByRole("button", { name: "Simpan kelas", exact: true }).click();
    await expect(page.getByRole("heading", { name: tag + "-Kelas", exact: true })).toBeVisible();
    const classURL = page.url().split("?")[0];
    await page.getByRole("navigation", { name: "Detail kelas" }).getByRole("link", { name: "Siswa", exact: true }).click();
    await page.getByRole("button", { name: "Tambah siswa", exact: true }).click();
    await page.getByLabel("Cari siswa untuk ditambahkan").fill(tag);
    await page.getByRole("checkbox", { name: new RegExp(tag + "-Siswa Edit") }).check();
    await page.getByRole("button", { name: "Tambahkan 1 siswa" }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toContainText("berhasil");
    await page.getByRole("button", { name: "Tutup dialog" }).click();
    await expect(page.getByRole("cell", { name: tag + "-Siswa Edit", exact: true })).toBeVisible();
    const studentProfile = () => page.getByRole("row").filter({hasText:tag + "-Siswa Edit"}).getByRole("link", {name:"Detail / Edit"});
    await studentProfile().click();
    await expect(page.getByRole("heading", {name:"Detail Pengguna",exact:true})).toBeVisible();
    await page.reload();
    await page.getByLabel("Tempat lahir", {exact:true}).fill("Perubahan dibatalkan");
    await page.getByRole("link", {name:"Batal",exact:true}).click();
    await expect(page).toHaveURL(classURL + "?tab=siswa");
    await studentProfile().click();
    await expect(page.getByLabel("Tempat lahir", {exact:true})).toHaveValue("Depok");
    await page.getByLabel(/^ID pengguna(?: \*)?$/).fill(tag + "-teacher");
    await page.getByRole("button", {name:"Simpan perubahan",exact:true}).click();
    await expect(page.getByRole("alert").filter({hasText:"sudah digunakan"})).toBeVisible();
    await expect(page.getByRole("link", {name:"Batal",exact:true})).toHaveAttribute("href", new URL(classURL).pathname + "?tab=siswa");
    await page.getByLabel(/^ID pengguna(?: \*)?$/).fill(tag + "-student");
    await page.getByLabel("Tempat lahir", {exact:true}).fill("Jakarta");
    await page.getByRole("button", {name:"Simpan perubahan",exact:true}).click();
    await expect(page).toHaveURL(classURL + "?tab=siswa&user_saved=1");
    await expect(page.getByRole("status")).toContainText("Perubahan data pengguna berhasil disimpan");
    await studentProfile().click();
    await expect(page.getByLabel("Tempat lahir", {exact:true})).toHaveValue("Jakarta");
    await page.getByRole("link", {name:"Batal",exact:true}).click();
    await page.getByRole("navigation", { name: "Detail kelas" }).getByRole("link", { name: "Guru", exact: true }).click();
    await page.getByRole("button", { name: "Tambah guru", exact: true }).click();
    await page.getByLabel(/^Guru(?: \*)?$/).selectOption({ label: tag + "-Guru · " + tag + "-teacher" });
    await page.getByRole("button", { name: "Simpan penugasan" }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toContainText("berhasil");
    await page.getByRole("button", { name: "Tutup dialog" }).click();
    await expect(page.getByRole("cell", { name: tag + "-Guru", exact: true })).toBeVisible();
    await expect(page.getByRole("row").filter({hasText: tag + "-Guru"}).getByRole("link", {name:"Detail / Edit"})).toBeVisible();
    const teacherProfile = () => page.getByRole("row").filter({hasText:tag + "-Guru"}).getByRole("link", {name:"Detail / Edit"});
    await teacherProfile().click();
    await page.getByRole("link", {name:"Batal",exact:true}).click();
    await expect(page).toHaveURL(classURL + "?tab=guru");
    await teacherProfile().click();
    await page.getByLabel("Nomor HP", {exact:true}).fill("081234567899");
    await page.getByRole("button", {name:"Simpan perubahan",exact:true}).click();
    await expect(page).toHaveURL(classURL + "?tab=guru&user_saved=1");
    await expect(page.getByRole("status")).toContainText("Perubahan data pengguna berhasil disimpan");
    await page.getByLabel("Filter penugasan guru").selectOption("subject_teacher");
    await expect(page.getByRole("heading", {name:"Belum ada guru yang sesuai"})).toBeVisible();
    await page.getByLabel("Filter penugasan guru").selectOption("homeroom");
    await page.getByLabel("Filter status guru").selectOption("inactive");
    await expect(page.getByRole("heading", {name:"Belum ada guru yang sesuai"})).toBeVisible();
    await page.getByLabel("Filter status guru").selectOption("active");
    await page.getByLabel("Filter mata pelajaran").selectOption("none");
    await expect(page.getByRole("cell", {name:tag + "-Guru",exact:true})).toBeVisible();
    await page.getByRole("navigation", { name: "Detail kelas" }).getByRole("link", { name: "Pengumuman", exact: true }).click();
    await page.getByRole("button", { name: "Buat pengumuman", exact: true }).click();
    await page.getByLabel("Judul pengumuman").fill("Informasi uji");
    await page.getByLabel("Isi pengumuman").fill("Pengumuman kelas untuk pengujian.");
    await page.getByRole("button", { name: "Terbitkan pengumuman" }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toContainText("berhasil");
    await page.getByRole("button", { name: "Tutup dialog" }).click();
    await expect(page.getByRole("heading", { name: "Informasi uji", exact: true })).toBeVisible();
    await page.goto(classURL + "/edit");
    await page.getByLabel(/^Nama ruang(?: \*)?$/).fill("Ruang revisi");
    await page.getByRole("button", { name: "Simpan perubahan kelas" }).click();
    await expect(page.getByText("Ruang revisi", { exact: true }).first()).toBeVisible();
    await page.screenshot({ path: "test-results/kelas-detail-admin.png", fullPage: true });
    await page.goto(classURL + "?tab=siswa");
    await page.getByRole("button", { name: "Keluarkan " + tag + "-Siswa Edit" }).click();
    await page.getByRole("button", { name: "Keluarkan dari kelas", exact: true }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toContainText("berhasil");
    await page.getByRole("button", { name: "Tutup dialog" }).click();
    await expect(page.getByRole("cell", { name: tag + "-Siswa Edit", exact: true })).toHaveCount(0);
    await page.goto(userURL); await expect(page.getByLabel(/^ID pengguna(?: \*)?$/)).toHaveValue(tag + "-student");
    await page.setViewportSize({ width: 390, height: 844 });
    for (const route of ["/pengguna/baru", "/pengguna/import", "/kelas/baru", classURL + "?tab=guru"]) {
      await page.goto(route); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    }
    await page.screenshot({ path: "test-results/kelas-mobile-admin.png", fullPage: true });
  });
  test("new management API endpoints reject student and anonymous access", async ({ request }) => {
    const api = "http://127.0.0.1:8080";
    const login = await request.post(api + "/auth/login", { data: { login_id: process.env.E2E_STUDENT_ID || "STD001", password: process.env.E2E_STUDENT_PASSWORD || "Belajar123!" } });
    expect(login.status()).toBe(200);
    const { token } = await login.json();
    for (const [method, path] of [["GET", "/api/academic-options"], ["PATCH", "/api/classes/1"], ["PATCH", "/api/users/1"], ["POST", "/api/users/import"], ["POST", "/api/classes/1/announcements"]]) {
      expect((await request.fetch(api + path, { method, headers: { Authorization: `Bearer ${token}` }, data: {} })).status()).toBe(403);
      expect((await request.fetch(api + path, { method, data: {} })).status()).toBe(401);
    }
  });
});
