import {test,expect} from "@playwright/test";
import {userReturnPath,userResultPath} from "../modules/users/return-path";
test.beforeEach(async({context,request})=>{
 await request.get("http://127.0.0.1:8088/__reset");
 await context.addCookies([{name:"ems_session",value:"isolated-admin-fixture",domain:"127.0.0.1",path:"/",httpOnly:true,sameSite:"Lax"}]);
});
test("return paths only accept user filters or class member tabs",()=>{
 for(const value of ["https://example.test","//example.test","/pengguna/901","/pengguna/../login","/kelas/1?tab=ringkasan",["/pengguna"],null])expect(userReturnPath(value)).toBeNull();
 expect(userReturnPath("/pengguna?role=teacher&status=active&q=Guru&redirect=https://example.test")).toBe("/pengguna?role=teacher&status=active&q=Guru");
 expect(userResultPath("/kelas/1?tab=guru","deleted")).toBe("/kelas/1?tab=guru&user_deleted=1");
});
test("create returns to filtered tab and next create form is empty",async({page})=>{
 await page.goto("/pengguna?role=teacher&status=active&q=Guru");
 await page.getByRole("link",{name:"Tambah pengguna",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Tambah Pengguna Baru"})).toBeVisible();
 await expect(page.getByRole("combobox",{name:"Peran pengguna",exact:true})).toHaveValue("teacher");
 await page.getByLabel("Nama lengkap").fill("Guru Baru");
 await page.getByLabel("Kata sandi awal").fill("FixtureOnly123!");
 await page.getByLabel("NIP / Nomor pegawai").fill("67890");
 await page.getByRole("button",{name:"Buat akun",exact:true}).click();
 await expect(page).toHaveURL(/\/pengguna\?role=teacher&status=active&q=Guru&created=1$/);
 await expect(page.getByRole("status")).toContainText("berhasil dibuat");
 await expect(page.getByRole("cell",{name:"GUR-AUTO",exact:true})).toBeVisible();
 await page.goBack();
 await expect(page.getByRole("heading",{name:"Tambah Pengguna Baru"})).toBeVisible();
 await expect(page.getByLabel("Nama lengkap")).toHaveValue("");
 await expect(page.getByLabel("Kata sandi awal")).toHaveValue("");
 await page.getByRole("link",{name:"Batal",exact:true}).click();
 await page.getByRole("link",{name:"Tambah pengguna",exact:true}).click();
 for(const label of ["Nama lengkap","Kata sandi awal","NIP / Nomor pegawai","Alamat email"])await expect(page.getByLabel(label)).toHaveValue("");
 await page.getByRole("link",{name:"Batal",exact:true}).click();
 await expect(page).toHaveURL(/\/pengguna\?role=teacher&status=active&q=Guru$/);
});
test("view edit and delete preserve list filters; class deletion returns to class",async({page})=>{
 await page.goto("/pengguna?role=teacher&status=active&q=Guru");
 await page.getByRole("link",{name:"Lihat Guru Pengujian",exact:true}).click();
 await expect(page.getByRole("textbox")).toHaveCount(0);
 await page.getByRole("link",{name:"Kembali",exact:true}).click();
 await page.getByRole("link",{name:"Edit Guru Pengujian",exact:true}).click();
 await page.getByLabel("Nama lengkap").fill("Guru Diperbarui");
 await page.getByRole("button",{name:"Simpan perubahan"}).click();
 await expect(page).toHaveURL(/role=teacher&status=active&q=Guru&saved=1$/);
 await page.getByRole("link",{name:"Edit Guru Diperbarui",exact:true}).click();
 await page.getByRole("button",{name:"Hapus pengguna Guru Diperbarui",exact:true}).click();
 await page.getByRole("dialog").getByRole("button",{name:"Ya, hapus"}).click();
 await expect(page).toHaveURL(/role=teacher&status=active&q=Guru&deleted=1$/);
 await expect(page.getByRole("status")).toContainText("dihapus");
 await page.request.get("http://127.0.0.1:8088/__reset");
 await page.goto("/pengguna/901?returnTo="+encodeURIComponent("/kelas/1?tab=guru"));
 await page.getByRole("button",{name:"Hapus pengguna Guru Pengujian",exact:true}).click();
 await page.getByRole("dialog").getByRole("button",{name:"Ya, hapus"}).click();
 await expect(page).toHaveURL(/kelas\/1\?tab=guru&user_deleted=1$/);
});
test("table delete confirmation and animated role marker",async({page})=>{
 await page.goto("/pengguna");
 const tabs=page.getByRole("navigation",{name:"Filter peran pengguna"});
 const line=tabs.locator(".tab-indicator");
 await expect(line).toHaveCSS("transition-duration","0.26s, 0.26s");
 const before=await line.evaluate(el=>getComputedStyle(el).transform);
 await tabs.getByRole("link",{name:"Guru",exact:true}).click();
 await expect(tabs.getByRole("link",{name:"Guru",exact:true})).toHaveAttribute("aria-current","page");
 await expect.poll(()=>line.evaluate(el=>getComputedStyle(el).transform)).not.toBe(before);
 await page.screenshot({path:"test-results/user-actions-desktop.png",fullPage:true});
 await page.getByRole("button",{name:"Hapus pengguna Guru Pengujian",exact:true}).click();
 await page.getByRole("dialog").getByRole("button",{name:"Batal",exact:true}).click();
 await expect(page.getByRole("cell",{name:"GURTEST",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Hapus pengguna Guru Pengujian",exact:true}).click();
 await page.getByRole("dialog").getByRole("button",{name:"Ya, hapus"}).click();
 await expect(page).toHaveURL(/role=teacher&deleted=1$/);
 await page.setViewportSize({width:390,height:844});
 await page.goto("/pengguna");
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:"test-results/user-actions-mobile.png",fullPage:true});
 await page.emulateMedia({reducedMotion:"reduce"});
 await expect(page.locator(".tab-indicator")).toHaveCSS("transition-duration","0s");
});
