"use client";
import { useState } from "react";
import { Modal } from "@/components/ui/modal";
import { Button, ButtonLink } from "@/components/ui/button";
import { ActionForm, Field, SelectField, TextField } from "@/components/ui/form";
import { EmptyState } from "@/components/empty-state";
import { statusLabels, type User } from "@/modules/users/types";
import { createAnnouncement, setMembers, setTeacher } from "./actions";
import type { AcademicOptions, ClassMember, ClassTeacher } from "./types";

export function ClassStudents({ classID, members, candidates }: { classID: number; members: ClassMember[]; candidates: User[] }) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [adding, setAdding] = useState(false); const [removing, setRemoving] = useState<ClassMember | null>(null);
  const filtered = members.filter(m => `${m.full_name} ${m.login_id} ${m.nis ?? ""}`.toLowerCase().includes(search.toLowerCase()) && (!status || m.status === status));
  const available = candidates.filter(u => u.status === "active" && !members.some(m => m.id === u.id));
  return <section className="panel table-panel"><div className="table-toolbar management-filters"><Field label="Cari siswa kelas" value={search} onChange={e => setSearch(e.target.value)} placeholder="Nama, ID, atau NIS…" /><SelectField label="Filter status siswa" value={status} onChange={e => setStatus(e.target.value)}><option value="">Semua status</option>{Object.entries(statusLabels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</SelectField><Button variant="primary" onClick={() => setAdding(true)}>Tambah siswa</Button></div>
    {!filtered.length ? <EmptyState icon="users" title="Belum ada siswa yang sesuai" description="Tambahkan siswa atau ubah pencarian Anda." /> : <div className="table-scroll"><table><thead><tr><th>Nama siswa</th><th>ID pengguna</th><th>NIS</th><th>Status akun</th><th>Aksi</th></tr></thead><tbody>{filtered.map(m => <tr key={m.id}><td><strong>{m.full_name}</strong></td><td>{m.login_id}</td><td>{m.nis || "—"}</td><td><span className={`badge ${m.status !== "active" ? "neutral" : ""}`}>{statusLabels[m.status]}</span></td><td><div className="button-row"><ButtonLink href={`/pengguna/${m.id}?returnTo=${encodeURIComponent(`/kelas/${classID}?tab=siswa`)}`}>Detail / Edit</ButtonLink><Button onClick={() => setRemoving(m)} aria-label={`Keluarkan ${m.full_name}`}>Keluarkan</Button></div></td></tr>)}</tbody></table></div>}<div className="table-footer">{filtered.length} dari {members.length} siswa</div>
    {adding && <Modal title="Tambahkan siswa ke kelas" onClose={() => setAdding(false)}>{available.length ? <StudentPicker classID={classID} users={available} /> : <><p>Semua siswa aktif sudah berada di kelas ini, atau belum ada akun siswa aktif.</p><ButtonLink href="/pengguna/baru">Buat akun siswa</ButtonLink></>}</Modal>}
    {removing && <Modal title="Keluarkan siswa dari kelas?" tone="danger" onClose={() => setRemoving(null)}><p><strong>{removing.full_name}</strong> akan kehilangan akses ke kelas ini. Akun sekolahnya tetap tersimpan.</p><ActionForm action={setMembers.bind(null, classID)} submitLabel="Keluarkan dari kelas" submitVariant="danger" cancel={<Button onClick={() => setRemoving(null)}>Batal</Button>}><input type="hidden" name="user_ids" value={removing.id} /><input type="hidden" name="status" value="removed" /></ActionForm></Modal>}
  </section>;
}
function StudentPicker({ classID, users }: { classID: number; users: User[] }) {
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<number[]>([]);
  return <ActionForm action={setMembers.bind(null, classID)} submitLabel={`Tambahkan ${selected.length} siswa`}><Field label="Cari siswa untuk ditambahkan" value={search} onChange={e => setSearch(e.target.value)} />{selected.map(id => <input type="hidden" name="user_ids" value={id} key={id} />)}<div className="selection-list">{users.filter(u => `${u.full_name} ${u.login_id}`.toLowerCase().includes(search.toLowerCase())).map(u => <label key={u.id}><input type="checkbox" checked={selected.includes(u.id)} disabled={selected.length >= 100 && !selected.includes(u.id)} onChange={e => setSelected(e.target.checked ? [...selected, u.id] : selected.filter(id => id !== u.id))} /><span><strong>{u.full_name}</strong><small>{u.login_id}</small></span></label>)}</div><p className="muted">{selected.length} dipilih · maksimal 100 siswa</p></ActionForm>;
}
export function ClassTeachers({ classID, teachers, candidates, options }: { classID: number; teachers: ClassTeacher[]; candidates: User[]; options: AcademicOptions }) {
  const [search, setSearch] = useState(""); const [adding, setAdding] = useState(false); const [removing, setRemoving] = useState<ClassTeacher | null>(null);
  const [selectedTeacher, setSelectedTeacher] = useState<number | undefined>();
  const [status, setStatus] = useState(""); const [assignment, setAssignment] = useState(""); const [subject, setSubject] = useState("");
  const subjects = options.subjects.filter(s => teachers.some(t => t.subject_id === s.id));
  const filtered = teachers.filter(t =>     `${t.full_name} ${t.subject_name ?? ""}`.toLowerCase().includes(search.toLowerCase()) && (!status || t.status === status) && (!assignment || t.role === assignment) && (!subject || String(t.subject_id ?? "none") === subject));
  return <section className="panel table-panel"><div className="table-toolbar management-filters"><Field label="Cari guru kelas" value={search} onChange={e => setSearch(e.target.value)} placeholder="Nama guru atau mata pelajaran…" /><SelectField label="Filter penugasan guru" value={assignment} onChange={e => setAssignment(e.target.value)}><option value="">Semua penugasan</option><option value="homeroom">Wali kelas</option><option value="subject_teacher">Guru mata pelajaran</option></SelectField><SelectField label="Filter mata pelajaran" value={subject} onChange={e => setSubject(e.target.value)}><option value="">Semua mata pelajaran</option><option value="none">Tanpa mata pelajaran</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</SelectField><SelectField label="Filter status guru" value={status} onChange={e => setStatus(e.target.value)}><option value="">Semua status</option>{Object.entries(statusLabels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</SelectField><Button variant="primary" onClick={() => {setSelectedTeacher(undefined); setAdding(true);}}>Tambah guru</Button></div>
    {!filtered.length ? <EmptyState icon="users" title="Belum ada guru yang sesuai" description="Tetapkan wali kelas dan guru mata pelajaran untuk kelas ini." /> : <div className="table-scroll"><table><thead><tr><th>Nama guru</th><th>Mata pelajaran</th><th>Penugasan</th><th>Status akun</th><th>Aksi</th></tr></thead><tbody>{filtered.map(t => <tr key={t.id}><td><strong>{t.full_name}</strong></td><td>{t.subject_name || "—"}</td><td><span className="role-badge">{t.role === "homeroom" ? "Wali kelas" : "Guru mata pelajaran"}</span></td><td>{statusLabels[t.status]}</td><td><div className="button-row"><ButtonLink href={`/pengguna/${t.teacher_user_id}?returnTo=${encodeURIComponent(`/kelas/${classID}?tab=guru`)}`}>Detail / Edit</ButtonLink><Button onClick={() => {setSelectedTeacher(t.teacher_user_id);setAdding(true);}}>Tambah mapel</Button><Button onClick={() => setRemoving(t)} aria-label={`Hapus penugasan ${t.full_name}`}>Hapus penugasan</Button></div></td></tr>)}</tbody></table></div>}<div className="table-footer">{filtered.length} dari {teachers.length} penugasan guru</div>
    {adding && <Modal title="Tetapkan guru kelas" onClose={() => setAdding(false)}><TeacherPicker initialTeacher={selectedTeacher} classID={classID} candidates={candidates.filter(u => u.status === "active")} options={options} /></Modal>}
    {removing && <Modal title="Hapus penugasan guru?" tone="danger" onClose={() => setRemoving(null)}><p>Hapus penugasan <strong>{removing.full_name}</strong> sebagai {removing.role === "homeroom" ? "wali kelas" : `guru ${removing.subject_name}`} pada kelas ini. Akunnya tetap tersimpan.</p><ActionForm action={setTeacher.bind(null, classID)} submitLabel="Konfirmasi hapus penugasan" submitVariant="danger" cancel={<Button onClick={() => setRemoving(null)}>Batal</Button>}><input type="hidden" name="teacher_user_id" value={removing.teacher_user_id} /><input type="hidden" name="subject_id" value={removing.subject_id ?? ""} /><input type="hidden" name="role" value={removing.role} /><input type="hidden" name="status" value="removed" /></ActionForm></Modal>}
  </section>;
}
function TeacherPicker({ classID, candidates, options, initialTeacher }: { classID: number; candidates: User[]; options: AcademicOptions; initialTeacher?: number }) {
  const [role, setRole] = useState(initialTeacher ? "subject_teacher" : "homeroom");
  if (!candidates.length) return <><p>Belum ada akun guru aktif.</p><ButtonLink href="/pengguna/baru">Buat akun guru</ButtonLink></>;
  return <ActionForm action={setTeacher.bind(null, classID)} submitLabel="Simpan penugasan"><SelectField label="Guru" name="teacher_user_id" required defaultValue={initialTeacher ?? ""}><option value="" disabled>Pilih guru</option>{candidates.map(u => <option key={u.id} value={u.id}>{u.full_name} · {u.login_id}</option>)}</SelectField><p className="muted">Guru yang sama dapat menjadi wali kelas sekaligus guru mapel. Gunakan Tambah mapel pada baris guru untuk penugasan tambahan.</p><SelectField label="Penugasan guru" name="role" value={role} onChange={e => setRole(e.target.value)}><option value="homeroom">Wali kelas</option><option value="subject_teacher">Guru mata pelajaran</option></SelectField>{role === "subject_teacher" ? <SelectField label="Mata pelajaran" name="subject_id" required defaultValue=""><option value="" disabled>Pilih mata pelajaran</option>{options.subjects.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</SelectField> : <p className="form-message">Menetapkan wali kelas baru akan menggantikan penugasan wali kelas sebelumnya.</p>}</ActionForm>;
}
export function AnnouncementControl({ classID }: { classID: number }) {
  const [open, setOpen] = useState(false);
  return <><Button variant="primary" onClick={() => setOpen(true)}>Buat pengumuman</Button>{open && <Modal title="Buat pengumuman kelas" onClose={() => setOpen(false)}><ActionForm action={createAnnouncement.bind(null, classID)} submitLabel="Terbitkan pengumuman"><Field label="Judul pengumuman" name="title" required maxLength={200} /><TextField label="Isi pengumuman" name="content" required maxLength={10000} /></ActionForm></Modal>}</>;
}
