import Link from "next/link";
import { Icon } from "@/components/icon";
import { monitoringClasses, monitoringSummary, monitoringProfile } from "@/modules/monitoring/data";

export async function CurriculumDashboard() {
  const [profile, classes, content] = await Promise.all([monitoringProfile(), monitoringClasses(), monitoringSummary()]);
  const students = new Set(classes.flatMap(c => c.members.map(m => m.id))).size;
  const teachers = new Set(classes.flatMap(c => c.teachers.map(t => t.teacher_user_id))).size;
  const needsAttention = classes.filter(c => !c.teachers.some(t => t.role === "homeroom" && t.status === "active") || !c.teachers.some(t => t.subject_id && t.status === "active"));
  return <><div className="page-heading"><div><span className="eyebrow">PORTAL KURIKULUM</span><h1>Selamat datang, {profile.full_name}.</h1><p>Pantau kesiapan kelas dan perkembangan pembelajaran sekolah.</p></div></div>
    <section className="welcome-card"><div><span className="welcome-tag">Pemantauan akademik</span><h2>Pembelajaran sekolah dalam satu ruang.</h2><p>Telusuri kelas, tinjau publikasi guru, dan lihat hasil pengumpulan tugas.</p><Link className="button white" href="/kelas">Pantau kelas <Icon name="arrow" /></Link></div><div className="welcome-art" aria-hidden="true"><Icon name="school" width={120} height={120} /></div></section>
    <div className="stats-grid">{[{label:"Kelas aktif",value:classes.length,icon:"classes" as const},{label:"Siswa dalam kelas",value:students,icon:"users" as const},{label:"Guru ditugaskan",value:teachers,icon:"school" as const}].map(s => <Link href="/kelas" className="stat-card" key={s.label}><span className="stat-icon blue"><Icon name={s.icon} /></span><div><span>{s.label}</span><strong>{s.value}</strong></div><Icon name="arrow" /></Link>)}</div>
    <div className="student-columns"><section className="panel"><div className="section-heading"><div><h2>Publikasi pembelajaran</h2><p className="muted">Perbandingan konten terbit terhadap seluruh konten yang tersedia.</p></div></div>{[{label:"Materi",href:"/materi",items:content.materials},{label:"Tugas",href:"/tugas",items:content.assignments},{label:"Asesmen",href:"/asesmen",items:content.assessments}].map(group => { const published = group.items.published; return <Link className="curriculum-progress" key={group.href} href={group.href}><span><strong>{group.label}</strong><small>{published} terbit / {group.items.total} total</small></span><progress value={published} max={group.items.total || 1} aria-label={`${group.label} diterbitkan`} /><small>{group.items.draft} draf</small></Link>; })}</section>
    <section className="panel"><h2>Perlu ditinjau</h2><p className="muted">Kelas yang belum memiliki wali kelas atau guru mapel aktif.</p>{needsAttention.length ? needsAttention.slice(0, 5).map(c => <Link className="student-dashboard-row" key={c.id} href={`/kelas/${c.id}?tab=guru`}><div><h3>{c.title}</h3><p>Periksa penugasan guru</p></div><Icon name="arrow" /></Link>) : <p>{classes.length ? "Semua kelas sudah memiliki wali dan guru mapel aktif." : "Belum ada kelas aktif untuk ditinjau."}</p>}</section></div>
    <section className="panel"><h2>Akses cepat</h2><div className="teacher-shortcuts"><Link href="/kelas"><Icon name="classes" /><strong>Monitoring kelas</strong><span>Lihat siswa dan penugasan guru.</span></Link><Link href="/laporan"><Icon name="task" /><strong>Laporan aktivitas</strong><span>Pantau siswa/guru dan ekspor Excel.</span></Link></div></section></>;
}
