import Link from "next/link";
import { notFound } from "next/navigation";
import { ButtonLink } from "@/components/ui/button";
import { Icon } from "@/components/icon";
import { studentClasses, studentContent, studentDetail, studentSubmissions } from "./data";
import { assessmentStatus, closed, date, learningLabels, learningPaths, safeURL } from "./helpers";
import { SubmissionForm } from "./submission-form";
import { classSubjects, subjectHref } from "./subjects";
import type { Kind } from "./types";

export async function StudentLearningDetail({kind,id,context,subjectContext}:{kind:Kind;id:string;context?:string;subjectContext?:string}) {
 const item=await studentDetail(kind,id);const classes=await studentClasses();
 let classroom=classes.find(c=>c.id===item.class_id);
 if(context){if(!/^[1-9]\d*$/.test(context))notFound();classroom=classes.find(c=>String(c.id)===context);if(!classroom)notFound();if(kind==="assessments"){if(!(await studentContent(kind,classroom.id)).some(i=>i.id===item.id))notFound();}else if(classroom.id!==item.class_id)notFound();}
 const subject=classroom?classSubjects(classroom).find(s=>s.id===item.subject_id):undefined;
 if(subjectContext&&(!/^[1-9]\d*$/.test(subjectContext)||!subject||String(subject.id)!==subjectContext))notFound();
 const back=classroom&&subject?`${subjectHref(classroom.id,subject.id)}?tab=${learningPaths[kind]}`:classroom?`/kelas?kelas=${classroom.id}`:`/${learningPaths[kind]}`;
 const submissions=kind==="assignments"?await studentSubmissions(item.id):[];const submission=submissions[0];const url=safeURL(item.url);
 return <div className="student-workspace"><Link className="text-link back-link" href={back}>← {subject?.name ?? classroom?.title ?? learningLabels[kind]}</Link><div className="page-heading"><div><span className="eyebrow">{learningLabels[kind]}{classroom?` · ${classroom.title}`:""}</span><h1>{item.title}</h1><p>{item.teacher_name}{item.published_at?` · ${date(item.published_at)}`:""}</p></div>{kind==="assessments"&&<span className="badge neutral">{assessmentStatus(item)}</span>}</div>
 <div className="student-columns"><div><section className="panel"><h2>{kind==="materials"?"Tentang materi":kind==="assignments"?"Petunjuk pengerjaan":"Tentang asesmen"}</h2><p className="preserve-lines">{item.description||"Belum ada keterangan tambahan dari guru."}</p>{kind==="materials"&&<div className="student-resource"><span className="icon-tile"><Icon name="book"/></span><div><h3>{item.title}</h3><p>{(item.type??"materi").toUpperCase()}{item.meeting_no?` · Pertemuan ${item.meeting_no}`:""}</p></div>{url?<a className="button primary" href={url} target="_blank" rel="noopener noreferrer">Buka sumber materi<Icon name="arrow" width={16}/></a>:<p className="muted">Sumber materi belum tersedia. Hubungi guru kelas.</p>}</div>}{kind==="assessments"&&<><h3>Petunjuk asesmen</h3><p className="preserve-lines">{item.instructions||"Petunjuk belum ditambahkan oleh guru."}</p></>}</section>
 {submission&&<section className="panel"><div className="section-heading"><h2>Jawaban Anda</h2><span className="badge">Sudah dikumpulkan</span></div><p className="muted">Dikirim {date(submission.submitted_at,true)}</p>{submission.submission_type==="link"&&safeURL(submission.link_url)?<a className="text-link student-wrap" href={safeURL(submission.link_url)!} target="_blank" rel="noopener noreferrer">{submission.link_url}</a>:<p className="preserve-lines">{submission.text_answer}</p>}</section>}</div>
 <aside><section className="panel"><h2>{kind==="assignments"?"Pengumpulan tugas":"Informasi"}</h2><dl className="detail-list"><div><dt>Guru</dt><dd>{item.teacher_name}</dd></div>{kind==="assignments"&&<><div><dt>Tenggat</dt><dd>{date(item.due_at,true)}</dd></div>{item.close_at&&<div><dt>Ditutup</dt><dd>{date(item.close_at,true)}</dd></div>}<div><dt>Nilai maksimal</dt><dd>{item.max_points??"Belum ditentukan"}</dd></div></>}{kind==="materials"&&<div><dt>Diterbitkan</dt><dd>{date(item.published_at)}</dd></div>}{kind==="assessments"&&<><div><dt>Jumlah soal</dt><dd>{item.question_count??0} soal</dd></div><div><dt>Durasi</dt><dd>{item.duration_minutes?`${item.duration_minutes} menit`:"Belum ditentukan"}</dd></div><div><dt>Mulai</dt><dd>{date(item.start_at,true)}</dd></div><div><dt>Selesai</dt><dd>{date(item.end_at,true)}</dd></div></>}</dl>
 {kind==="assignments"&&(submission?<><div className="student-grade"><span>Nilai tugas</span><strong>{submission.result_released_at&&submission.score!==null?submission.score:"—"}</strong><small>{submission.result_released_at?"Nilai telah dirilis oleh guru":"Menunggu penilaian guru"}</small></div>{submission.result_released_at&&submission.teacher_feedback&&<><h3>Umpan balik guru</h3><p className="preserve-lines">{submission.teacher_feedback}</p></>}</>:closed(item)?<p className="form-message error">Pengumpulan tugas sudah ditutup. Hubungi guru jika Anda membutuhkan bantuan.</p>:<SubmissionForm id={item.id} title={item.title}/>)}
 {kind==="assessments"&&<p className="form-message">Pengerjaan asesmen belum tersedia di portal ini. Jadwal dan petunjuk dapat dilihat di atas; hubungi guru untuk arahan pelaksanaan.</p>}
 </section><ButtonLink href={back}>Kembali ke {subject?"mapel":classroom?"kelas":learningLabels[kind].toLowerCase()}</ButtonLink></aside></div></div>;
}
