import { ButtonLink } from "@/components/ui/button";
import { ActionForm, Field, TextField } from "@/components/ui/form";
import { studentClasses, studentProfile } from "./data";
import { saveStudentProfile } from "./actions";
import { initials } from "./helpers";
export async function StudentProfile({saved}:{saved:boolean}) {
 const [profile,classes]=await Promise.all([studentProfile(),studentClasses()]);
 return <div className="student-workspace"><div className="page-heading"><div><h1>Profil Saya</h1><p>Identitas dan informasi akun sekolah Anda.</p></div></div>{saved&&<p className="form-message success" role="status">Profil berhasil diperbarui.</p>}<div className="student-profile-grid"><aside className="panel student-profile-summary"><span className="student-profile-avatar">{initials(profile.full_name)}</span><h2>{profile.full_name}</h2><span className="badge neutral">Siswa</span><p>{profile.login_id}</p><p className="preserve-lines">{profile.bio||"Belum ada bio."}</p></aside><div><section className="panel"><h2>Informasi pribadi</h2><p>Perbarui nama tampilan dan ceritakan sedikit tentang diri Anda.</p><ActionForm action={saveStudentProfile} submitLabel="Simpan perubahan" cancel={<ButtonLink href="/dashboard">Batal</ButtonLink>}><Field label="Nama lengkap" name="full_name" required maxLength={150} defaultValue={profile.full_name}/><TextField label="Bio" name="bio" maxLength={1000} defaultValue={profile.bio??""}/></ActionForm></section><section className="panel"><h2>Identitas sekolah</h2><p className="muted">Hubungi admin sekolah jika identitas berikut perlu diperbarui.</p><dl className="detail-list"><div><dt>ID pengguna</dt><dd>{profile.login_id}</dd></div><div><dt>Email</dt><dd>{profile.email||"Belum diisi"}</dd></div><div><dt>NIS</dt><dd>{profile.nis||"Belum diisi"}</dd></div><div><dt>NISN</dt><dd>{profile.nisn||"Belum diisi"}</dd></div><div><dt>Kelas yang diikuti</dt><dd>{classes.map(c=>c.title).join(", ")||"Belum bergabung dengan kelas"}</dd></div></dl></section></div></div></div>;
}
