"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Field, SelectField, TextField, type FormState } from "@/components/ui/form";
import { Modal } from "@/components/ui/modal";
import { submitStudentTask } from "./actions";
export function SubmissionForm({id,title}:{id:number;title:string}) {
 const [type,setType]=useState("text");const [text,setText]=useState("");const [link,setLink]=useState("");const [confirm,setConfirm]=useState(false);const [state,setState]=useState<FormState>({});const [pending,start]=useTransition();const router=useRouter();
 const send=()=>start(async()=>{const data=new FormData();data.set("submission_type",type);data.set("answer",type==="text"?text:link);const result=await submitStudentTask(id,{},data);setState(result);setConfirm(false);if(result.success)router.refresh();});
 return <>{state.error&&<p className="form-message error" role="alert">{state.error}</p>}{state.success?<p className="form-message success" role="status">{state.success}</p>:<form className="management-form" onSubmit={e=>{e.preventDefault();setConfirm(true);}}><fieldset disabled={pending}><SelectField label="Bentuk jawaban" value={type} onChange={e=>setType(e.target.value)}><option value="text">Teks jawaban</option><option value="link">Tautan</option></SelectField>{type==="text"?<TextField label="Jawaban Anda" required value={text} onChange={e=>setText(e.target.value)} maxLength={60000} rows={8}/>:<Field label="Tautan jawaban" type="url" required value={link} onChange={e=>setLink(e.target.value)} maxLength={500} placeholder="https://…" hint="Pastikan guru memiliki akses untuk membuka tautan Anda."/>}<p className="muted">Periksa jawaban Anda. Tugas yang sudah dikumpulkan belum dapat diganti.</p><Button type="submit" variant="primary" disabled={pending}>Kumpulkan tugas</Button></fieldset></form>}{confirm&&<Modal title="Kumpulkan tugas sekarang?" onClose={()=>{if(!pending)setConfirm(false);}}><p>Jawaban untuk <strong>{title}</strong> akan dikirim kepada guru.</p><div className="student-answer-preview preserve-lines">{type==="text"?text:link}</div><p className="muted">Jawaban tidak dapat diubah setelah dikumpulkan.</p><div className="form-actions"><Button disabled={pending} onClick={()=>setConfirm(false)}>Periksa lagi</Button><Button variant="primary" disabled={pending} onClick={send}>{pending?"Mengirim…":"Ya, kumpulkan"}</Button></div></Modal>}</>;
}
