import Link from "next/link";
import { backend } from "@/lib/api";
import { monitoringSession } from "./data";
import { classWorkspace } from "@/modules/classes/data";
import { ActivityPanel } from "./activity-panel";
import type { ActivityReport } from "./activity-types";
export async function ActivityPage({from,to,classID}:{from?:string;to?:string;classID?:string}){
 const {token,identity}=await monitoringSession();const query=new URLSearchParams();if(from)query.set("from",from);if(to)query.set("to",to);if(classID)query.set("class_id",classID);
 let report:ActivityReport;let classes:Awaited<ReturnType<typeof classWorkspace>>;
 try{[classes,report]=await Promise.all([classWorkspace(token,true),backend<ActivityReport>(`/api/monitoring/report?${query}`,{token,timeout:35000})]);}catch(error){return <section className="panel"><h1>Laporan aktivitas</h1><p role="alert" className="form-message error">{error instanceof Error?error.message:"Laporan belum tersedia."}</p><Link className="button" href="/laporan">Kembali ke periode awal</Link></section>;}
 const exportQuery=new URLSearchParams({from:report.from,to:report.to});if(classID)exportQuery.set("class_id",classID);
 return <><div className="page-heading"><div><span className="eyebrow">PEMANTAUAN PEMBELAJARAN</span><h1>Aktivitas & perkembangan</h1><p>Pantau partisipasi siswa dan aktivitas guru berdasarkan rekaman pembelajaran.</p></div><a className="button primary" href={`/api/monitoring/export?${exportQuery}`}>Ekspor Excel (.xlsx)</a></div><nav className="tabs" aria-label="Jenis laporan"><Link href="/laporan" className="selected" aria-current="page">Aktivitas & tindak lanjut</Link><Link href="/laporan?mode=tugas">Rincian per tugas</Link></nav><section className="panel"><form autoComplete="off" method="get" action="/laporan" className="curriculum-filters"><div className="form-field"><label htmlFor="activity-from">Tanggal awal</label><input id="activity-from" name="from" type="date" required defaultValue={report.from}/></div><div className="form-field"><label htmlFor="activity-to">Tanggal akhir</label><input id="activity-to" name="to" type="date" required defaultValue={report.to}/></div><div className="form-field"><label htmlFor="activity-class">Kelas</label><select id="activity-class" name="kelas" defaultValue={classID??""}><option value="">Semua kelas aktif</option>{classes.map(c=><option key={c.id} value={c.id}>{c.title} · {c.year}</option>)}</select></div><button className="button" type="submit">Terapkan periode</button></form><p className="muted">Excel mengikuti periode dan kelas di atas, berisi lembar siswa, guru, rincian aktivitas, tren, dan catatan tindak lanjut.</p></section><ActivityPanel key={`${report.from}/${report.to}/${classID}`} report={report} canReview={identity.role==="curriculum"}/></>;
}
