"use client";
import { ActivityDonuts } from "./activity-donuts";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Field, SelectField, TextField } from "@/components/ui/form";
import { Modal } from "@/components/ui/modal";
import { date, learningPaths } from "@/modules/student/helpers";
import { addActivityReview } from "./activity-actions";
import type { ActivityReport, ActivityRow } from "./activity-types";
const reviewLabels={review:"Perlu ditinjau",monitor:"Dalam pendampingan",resolved:"Tindak lanjut selesai"};
const needsReview=(r:ActivityRow)=>r.reasons.length>0||r.review_status==="review"||r.review_status==="monitor";
const rowKey=(r:ActivityRow)=>`${r.user_id}/${r.class_id}/${r.subject_id}`;
export function ActivityPanel({report,canReview}:{report:ActivityReport;canReview:boolean}){
 const [tab,setTab]=useState<"students"|"teachers">("students"),[query,setQuery]=useState(""),[attention,setAttention]=useState(false),[selected,setSelected]=useState<ActivityRow|null>(null),[status,setStatus]=useState("review"),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const router=useRouter();
 const [metric,setMetric]=useState<"published"|"submitted"|"opened">("submitted");
 const [teacherMetric,setTeacherMetric]=useState<"published"|"graded"|"pending_grade">("published");
 const teacherBars=[...new Set(report.teachers.map(r=>r.user_id))].map(id=>{const items=report.teachers.filter(r=>r.user_id===id);return {id,name:items[0].name,value:items.reduce((n,r)=>n+(teacherMetric==="published"?r.materials+r.tasks+r.exams:r[teacherMetric]),0)};}).sort((a,b)=>a.name.localeCompare(b.name,"id"));
 const teacherMax=Math.max(1,...teacherBars.map(r=>r.value));
 const rows=report[tab].filter(r=>(!attention||needsReview(r))&&`${r.name} ${r.identifier} ${r.subject} ${r.teachers}`.toLowerCase().includes(query.trim().toLowerCase()));
 const count=(key:"tasks"|"submitted"|"overdue"|"pending_grade")=>report.students.reduce((n,r)=>n+r[key],0);
 const classRows=[...new Set(report.students.map(r=>r.class_id))].map(id=>{const items=report.students.filter(r=>r.class_id===id);return {id,name:items[0].class_name,total:items.reduce((n,r)=>n+r.tasks,0),done:items.reduce((n,r)=>n+r.submitted,0)};});
 const max=Math.max(1,...report.days.map(d=>d[metric]));
 async function save(){if(!selected)return;setBusy(true);setError("");try{const result=await addActivityReview({user_id:selected.user_id,class_id:selected.class_id,subject_id:selected.subject_id,status,note});if(result.error){setError(result.error);return;}setSelected(null);setNote("");router.refresh();}catch{setError("Catatan belum tersimpan. Coba kembali.");}finally{setBusy(false);}}
 const reviews=selected?report.reviews.filter(r=>r.user_id===selected.user_id&&r.class_id===selected.class_id&&r.subject_id===selected.subject_id):[];
 return <div className="activity-workspace"><div className="stats-grid">{[{label:"Siswa perlu ditinjau",value:new Set(report.students.filter(needsReview).map(r=>r.user_id)).size},{label:"Tugas siswa belum masuk · lewat tenggat",value:count("overdue")},{label:"Jawaban menunggu penilaian",value:count("pending_grade")}].map(v=><div className="stat-card" key={v.label}><div><span>{v.label}</span><strong>{v.value}</strong></div></div>)}</div>
 <div className="student-columns"><section className="panel"><div className="section-heading"><div><h2>Tren aktivitas harian</h2><p className="muted">Rekaman dalam periode terpilih · WIB</p></div></div><SelectField label="Aktivitas pada grafik" value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}><option value="submitted">Jawaban dikumpulkan</option><option value="published">Konten terbit / asesmen dimulai</option><option value="opened">Materi pertama dibuka</option></SelectField>{report.days.length?<><svg className="activity-chart" viewBox="0 0 600 180" role="img" aria-label={`Grafik harian: total ${report.days.reduce((n,d)=>n+d[metric],0)} aktivitas`}><line x1="20" y1="150" x2="580" y2="150" stroke="#dce3ef"/><text x="0" y="20" fontSize="12">{max}</text><text x="5" y="150" fontSize="12">0</text><polyline fill="none" stroke="#397ee8" strokeWidth="3" points={report.days.map((d,i)=>`${25+i*550/Math.max(report.days.length-1,1)},${150-d[metric]/max*125}`).join(" ")}/>{report.days.map((d,i)=><circle key={d.day} cx={25+i*550/Math.max(report.days.length-1,1)} cy={150-d[metric]/max*125} r="3" fill="#397ee8"><title>{d.day}: {d[metric]}</title></circle>)}</svg><div className="section-heading muted"><small>{report.from}</small><small>{report.to}</small></div><details><summary>Lihat angka harian</summary><div className="table-scroll activity-day-table"><table><thead><tr><th>Tanggal</th><th>Jumlah</th></tr></thead><tbody>{report.days.map(d=><tr key={d.day}><td>{d.day}</td><td>{d[metric]}</td></tr>)}</tbody></table></div></details></>:<p>Belum ada aktivitas.</p>}</section>
 <section className="panel"><h2>Pengumpulan tugas per kelas</h2><p className="muted">Jawaban masuk dibanding kewajiban tugas siswa aktif.</p>{classRows.length?classRows.map(c=><div className="activity-class-bar" key={c.id}><div className="section-heading"><strong>{c.name}</strong><span>{c.done}/{c.total} · {c.total?`${Math.round(c.done/c.total*100)}%`:"Belum ada tugas"}</span></div><progress value={c.done} max={c.total||1} aria-label={`Pengumpulan tugas ${c.name}`}/></div>):<p>Belum ada siswa dan mapel aktif pada pilihan ini.</p>}</section></div>
 <section className="panel"><h2>Aktivitas guru</h2><p className="muted">Jumlah aktivitas per guru pada kelas yang dipilih. Grafik menampilkan 10 nama pertama; seluruh guru tersedia di tabel dan Excel.</p><SelectField label="Ukuran aktivitas guru" value={teacherMetric} onChange={e=>setTeacherMetric(e.target.value as typeof teacherMetric)}><option value="published">Konten terbit / asesmen dimulai</option><option value="graded">Jawaban sudah dinilai</option><option value="pending_grade">Jawaban menunggu penilaian</option></SelectField>{teacherBars.slice(0,10).map(r=><div className="activity-class-bar" key={r.id}><div className="section-heading"><strong>{r.name}</strong><span>{r.value}</span></div><progress max={teacherMax} value={r.value} aria-label={`Aktivitas ${r.name}: ${r.value}`}/></div>)}{!teacherBars.length&&<p>Belum ada guru mapel pada pilihan ini.</p>}</section>
 <ActivityDonuts report={report}/><section className="panel activity-method"><details><summary>Cara membaca laporan & penanda</summary><p>Anggota kelas dan penugasan guru menggunakan kondisi saat laporan dibuat. Materi/tugas mengikuti tanggal terbit; asesmen mengikuti tanggal mulai. Kewajiban siswa hanya dihitung untuk konten sejak siswa bergabung. Konten yang dihapus tidak dihitung sebagai kewajiban.</p><p>Pencatatan pembukaan materi dimulai {date(report.tracking_since,true)}. Membuka halaman tidak membuktikan materi selesai dibaca atau dipahami. Penanda akses hanya memakai materi yang terbit sejak pencatatan dimulai dan telah berumur minimal 7 hari.</p><p>Perlu ditinjau: minimal 3 tugas lewat tenggat belum masuk atau kurang dari 50% materi layak dipantau tercatat dibuka. Ini petunjuk untuk pendampingan; periksa akses internet, kondisi siswa, dan arahan guru terlebih dahulu.</p><p>Rata-rata memakai nilai yang sudah dirilis dan dinormalisasi menjadi 0–100. Nilai yang belum tersedia tidak dihitung sebagai nol. Banyaknya unggahan atau tugas bukan ukuran tunggal kualitas guru. Tren publikasi asesmen dihitung per kelas tujuan.</p></details></section>
 <section className="panel table-panel"><nav className="tabs" aria-label="Subjek pemantauan"><button type="button" className={tab==="students"?"selected":""} onClick={()=>{setTab("students");setAttention(false);}}>Siswa</button><button type="button" className={tab==="teachers"?"selected":""} onClick={()=>{setTab("teachers");setAttention(false);}}>Guru</button></nav><div className="curriculum-filters"><Field label="Cari nama, ID, atau mapel" type="search" value={query} onChange={e=>setQuery(e.target.value)}/>{tab==="students"&&<label className="teacher-check"><input type="checkbox" checked={attention} onChange={e=>setAttention(e.target.checked)}/> Hanya perlu ditinjau</label>}</div><div className="table-scroll"><table><thead><tr><th>{tab==="students"?"Siswa":"Guru"}</th><th>Kelas / mapel</th>{tab==="students"?<><th>Materi dibuka</th><th>Tugas masuk</th><th>Lewat tenggat</th><th>Asesmen masuk</th><th>Rata-rata /100</th><th>Penanda</th></>:<><th>Materi</th><th>Tugas</th><th>Asesmen</th><th>Jawaban dinilai</th><th>Menunggu penilaian</th></>}<th>Rincian</th></tr></thead><tbody>{rows.map(r=><tr key={rowKey(r)}><td><strong>{r.name}</strong><small className="activity-subtext">{r.identifier}</small>{r.review_status&&<small className="activity-subtext">{reviewLabels[r.review_status]}</small>}</td><td>{r.class_name}<small className="activity-subtext">{r.subject}</small></td>{tab==="students"?<><td>{r.opened}/{r.materials}</td><td>{r.submitted}/{r.tasks}</td><td>{r.overdue}</td><td>{r.exam_done}/{r.exams}</td><td>{r.average===null?"Belum ada nilai":r.average.toLocaleString("id-ID",{maximumFractionDigits:1})}</td><td><span className={`badge ${r.reasons.length?"neutral":""}`}>{r.reasons.length?"Perlu ditinjau":r.tasks||r.trackable?"Belum ada penanda":"Data belum cukup"}</span></td></>:<><td>{r.materials}</td><td>{r.tasks}</td><td>{r.exams}</td><td>{r.graded}</td><td>{r.pending_grade}</td></>}<td><Button onClick={()=>{setSelected(r);setNote("");setStatus("review");setError("");}}>Lihat rincian</Button></td></tr>)}</tbody></table></div>{!rows.length&&<p className="curriculum-filters">Belum ada data yang sesuai filter.</p>}<div className="table-footer">{rows.length} baris per pengguna, kelas, dan mapel. Pencarian hanya menyaring tabel; grafik dan Excel memakai seluruh periode/kelas.</div></section>
 <section className="panel"><h2>Riwayat tindak lanjut</h2><p className="muted">Riwayat catatan sampai tanggal akhir yang dipilih, termasuk pendampingan dari periode sebelumnya. Kepala sekolah dapat melihat dan mengekspor.</p>{report.reviews.length?report.reviews.map(r=><article className="activity-review" key={r.id}><strong>{r.name} · {reviewLabels[r.status]}</strong><p className="preserve-lines">{r.note}</p><small>{r.author} · {date(r.at,true)}</small></article>):<p>Belum ada catatan pada periode ini.</p>}</section>
 {selected&&<Modal title={`Rincian ${selected.name}`} onClose={()=>!busy&&setSelected(null)}><p>{selected.class_name} · {selected.subject}</p>{selected.teachers&&<p>Guru mapel: {selected.teachers}</p>}{selected.reasons.length>0&&<div className="form-message"><strong>Alasan peninjauan</strong><ul>{selected.reasons.map(r=><li key={r}>{r}</li>)}</ul></div>}<div className="activity-modal-scroll">{selected.evidence.length?<ul>{selected.evidence.map(e=><li key={`${e.kind}/${e.id}`}><Link href={`/${learningPaths[e.kind]}/${e.id}`}>{e.title}</Link><p className="muted">{e.status}</p></li>)}</ul>:<p>{tab==="teachers"?`${selected.materials} materi, ${selected.tasks} tugas, ${selected.exams} asesmen. ${selected.pending_grade} jawaban masih menunggu penilaian. ${selected.deleted} konten telah dihapus.`:"Belum ada kewajiban tercatat pada periode ini."}</p>}{reviews.map(r=><article className="activity-review" key={r.id}><strong>{reviewLabels[r.status]}</strong><p>{r.note}</p><small>{r.author} · {date(r.at,true)}</small></article>)}</div>{canReview&&<form autoComplete="off" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><h3>Catat tindak lanjut</h3><SelectField label="Status tindak lanjut" value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(reviewLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</SelectField><TextField label="Catatan pendampingan / peninjauan" required maxLength={1000} rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Tuliskan temuan, konteks, dan tindak lanjut yang perlu dilakukan."/>{error&&<p className="form-message error" role="alert">{error}</p>}<div className="form-actions"><Button type="submit" variant="primary">{busy?"Menyimpan…":"Simpan tindak lanjut"}</Button></div></fieldset></form>}</Modal>}
 </div>;
}
