import { AttentionPanel } from "@/modules/learning/attention";
import Link from "next/link";
import { teacherClasses, teacherContent, teacherProfile, teacherRequestTime } from "./data";
import { date, initials } from "@/modules/student/helpers";
import { EmptyState } from "@/components/empty-state";
import { Icon } from "@/components/icon";

export async function TeacherDashboard() {
  const [profile,classes,materials,tasks]=await Promise.all([teacherProfile(),teacherClasses(),teacherContent("materials"),teacherContent("assignments")]);
  const homerooms=classes.filter(c=>c.teachers.some(t=>t.teacher_user_id===profile.id&&t.status==="active"&&t.role==="homeroom"));
  const now=teacherRequestTime();
  const upcoming=tasks.filter(t=>t.status==="published"&&t.due_at&&new Date(t.due_at).getTime()>now).sort((a,b)=>a.due_at!.localeCompare(b.due_at!)).slice(0,5);
  return <div className="student-workspace teacher-workspace"><div className="page-heading"><div><h1>Selamat datang, {profile.full_name}.</h1><p>Ruang kerja untuk mengajar dan mendampingi siswa.</p></div></div><section className="student-welcome"><div><span>PORTAL GURU</span><h2>{classes.length} kelas dalam pendampingan Anda</h2><p>{homerooms.length?`Wali kelas: ${homerooms.map(c=>c.title).join(", ")}`:"Penugasan sebagai guru mata pelajaran"}</p><Link href="/kelas" className="button white">Buka kelas ajar <Icon name="arrow" width={18}/></Link></div><div className="student-welcome-stats"><Link href="/materi"><strong>{materials.length}</strong><span>Materi Anda</span></Link><Link href="/tugas"><strong>{tasks.length}</strong><span>Tugas Anda</span></Link></div></section><AttentionPanel/><div className="student-columns"><div><section className="panel"><div className="section-heading"><h2>Kelas ajar</h2><Link className="text-link" href="/kelas">Lihat semua</Link></div>{classes.length?classes.slice(0,4).map(c=><Link key={c.id} className="student-dashboard-row" href={`/kelas/${c.id}`}><span className="student-class-avatar small">{initials(c.title)}</span><div><h3>{c.title}</h3><p>{c.year} · {c.member_count} siswa</p></div><span className="badge neutral">{homerooms.some(h=>h.id===c.id)?"Wali kelas":"Guru mapel"}</span></Link>):<EmptyState title="Belum ada kelas ajar" description="Hubungi admin untuk mengatur penugasan Anda."/>}</section><section className="panel"><h2>Siapkan pembelajaran</h2><div className="teacher-shortcuts"><Link href="/kelas"><Icon name="book"/><strong>Materi dan tugas baru</strong><span>Pilih kelas dan mapel yang Anda ampu.</span></Link><Link href="/tugas"><Icon name="task"/><strong>Periksa jawaban siswa</strong><span>Buka tugas untuk menilai dan merilis hasil.</span></Link></div></section></div><aside><section className="panel"><h2>Tenggat mendatang</h2>{upcoming.length?<div className="student-timeline">{upcoming.map(t=><Link href={`/tugas/${t.id}`} key={t.id}><small>{date(t.due_at,true)}</small><h3>{t.title}</h3><p>{classes.find(c=>c.id===t.class_id)?.title}</p></Link>)}</div>:<p className="muted">Belum ada tenggat tugas mendatang.</p>}</section><section className="panel"><h2>Penugasan wali kelas</h2>{homerooms.length?homerooms.map(c=><Link key={c.id} className="student-dashboard-row" href={`/kelas/${c.id}?tab=siswa`}><div><h3>{c.title}</h3><p>Lihat siswa dan informasi kelas.</p></div><Icon name="arrow" width={18}/></Link>):<p className="muted">Anda belum ditugaskan sebagai wali kelas.</p>}</section></aside></div></div>;
}
