"use client";
import { useState } from "react";
import { Attachments } from "@/modules/assignments/attachments";
import { ActionForm, Field, TextField, SelectField } from "@/components/ui/form";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import type { ClassMember } from "@/modules/classes/types";
import type { TeacherSubmission } from "./data";
import { gradeAnswer, releaseAnswer } from "./actions";
import { date, safeURL } from "@/modules/student/helpers";

export function TeacherSubmissions({assignmentID,items,members,maxPoints,dueAt}:{dueAt:string|null;assignmentID:number;items:TeacherSubmission[];members:ClassMember[];maxPoints:number}) {
  const [query,setQuery]=useState(""); const [status,setStatus]=useState(""); const [selected,setSelected]=useState<number|null>(null);
  const entries=[...members.map(m=>({id:m.id,name:m.full_name,nis:m.nis,submission:items.find(s=>s.student_user_id===m.id)})),...items.filter(s=>!members.some(m=>m.id===s.student_user_id)).map(s=>({id:s.student_user_id,name:`Siswa #${s.student_user_id} (riwayat)`,nis:undefined,submission:s}))];
  const label=(s?:TeacherSubmission)=>!s?"Belum mengumpulkan":s.result_released_at?"Nilai dirilis":s.status==="graded"?"Sudah dinilai":"Perlu dinilai";
  const timing=(s?:TeacherSubmission)=>!s?"—":(s.is_late??(!!s.submitted_at&&!!dueAt&&Date.parse(s.submitted_at)>Date.parse(dueAt)))?"Terlambat":"Tepat waktu";
  const filtered=entries.filter(e=>`${e.name} ${e.nis||""}`.toLowerCase().includes(query.toLowerCase())&&(!status||label(e.submission)===status));
  const selectedEntry=entries.find(e=>e.submission?.id===selected); const answer=selectedEntry?.submission;
  return <section className="panel"><div className="section-heading"><div><h2>Pengumpulan siswa</h2><p className="muted">Periksa jawaban, simpan nilai, lalu rilis hasilnya kepada siswa.</p></div><span className="count-pill">{items.length} jawaban</span></div><div className="student-filters"><Field label="Cari siswa" value={query} onChange={e=>setQuery(e.target.value)}/><SelectField label="Status pengumpulan" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{["Belum mengumpulkan","Perlu dinilai","Sudah dinilai","Nilai dirilis"].map(s=><option key={s}>{s}</option>)}</SelectField></div><div className="table-scroll"><table><thead><tr><th>Siswa</th><th>Status penilaian</th><th>Waktu pengumpulan</th><th>Nilai</th><th>Aksi</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><strong>{e.name}</strong><small className="student-block muted">{e.nis||"—"}</small></td><td><span className="badge neutral">{label(e.submission)}</span></td><td><span className="badge neutral">{timing(e.submission)}</span>{e.submission&&<small className="student-block muted">{date(e.submission.submitted_at,true)}</small>}</td><td>{e.submission?.score??"—"}</td><td>{e.submission?<Button onClick={()=>setSelected(e.submission!.id)}>Periksa jawaban</Button>:"—"}</td></tr>)}</tbody></table></div>{!filtered.length&&<p className="muted">Tidak ada siswa yang sesuai.</p>}
  {answer&&selectedEntry&&<Modal title={`Jawaban ${selectedEntry.name}`} onClose={()=>setSelected(null)}><p className="muted">{timing(answer)} · Dikumpulkan {date(answer.submitted_at,true)}</p><div className="student-answer-preview">{answer.submission_type==="link"&&safeURL(answer.link_url)?<a className="text-link" target="_blank" rel="noopener noreferrer" href={safeURL(answer.link_url)!}>{answer.link_url}</a>:<p className="preserve-lines">{answer.text_answer}</p>}<Attachments items={answer.files} title="File jawaban"/></div>{answer.result_released_at?<><p className="form-message success">Nilai {answer.score} / {maxPoints} sudah dirilis.</p><p>{answer.teacher_feedback}</p></>:<><ActionForm key={`${answer.id}-${answer.score}-${answer.teacher_feedback}`} action={gradeAnswer.bind(null,assignmentID,answer.id)} submitLabel="Simpan nilai"><Field label="Nilai" name="score" type="number" min={0} max={maxPoints} step="0.01" required defaultValue={answer.score??""} hint={`Nilai maksimal ${maxPoints}`}/><TextField label="Umpan balik" name="teacher_feedback" defaultValue={answer.teacher_feedback??""} maxLength={10000}/></ActionForm>{answer.status==="graded"&&<div className="teacher-release"><p>Rilis nilai {answer.score} / {maxPoints} kepada {selectedEntry.name}? Setelah dirilis, nilai tidak dapat diedit melalui halaman ini.</p><ActionForm action={releaseAnswer.bind(null,assignmentID,answer.id)} submitLabel="Ya, rilis nilai"><span className="muted">Pastikan nilai dan umpan balik sudah sesuai.</span></ActionForm></div>}</>}</Modal>}
  </section>;
}
