"use client";
import { useState } from "react";
import { QuestionComposer, QuestionSettings, type QuestionDefaults } from "./question-composer";
import { useRouter } from "next/navigation";
import { Button, ButtonLink } from "@/components/ui/button";
import { Field, SelectField, TextField } from "@/components/ui/form";
import { Modal } from "@/components/ui/modal";
import { saveAssessment, publishAssessment } from "./actions";
import { questionLabels, type ExamDraft, type ExamQuestion, type TeachingChoice } from "./types";

const steps=["Informasi","Kelas & jadwal","Susun soal","Pratinjau"];
function localDate(value:string|null){return value?new Date(new Date(value).getTime()+7*3600000).toISOString().slice(0,16):"";}
function utcDate(value:string){return value?new Date(`${value}:00+07:00`).toISOString():null;}
export function QuestionPreview({questions,keys=false}:{questions:ExamQuestion[];keys?:boolean}){return <div className="exam-question-list">{questions.map((q,i)=><article className="exam-question" key={i}><div className="section-heading"><h3>Soal {i+1}</h3><span className="badge neutral">{questionLabels[q.type]} · {q.points} poin</span></div><p className="preserve-lines">{q.text||"Pertanyaan belum diisi."}</p>{q.type==="essay"?<p className="muted">Jawaban uraian · dinilai oleh guru</p>:<ol className="exam-options" type="A">{q.options.map((o,j)=><li key={j} className={keys&&o.correct?"exam-correct":""}>{o.text||"Pilihan belum diisi"}{keys&&o.correct&&<span> · Kunci jawaban</span>}</li>)}</ol>}</article>)}</div>;}
export function AssessmentEditor({initial,classes,back="/asesmen"}:{initial:ExamDraft;classes:TeachingChoice[];back?:string}){
 const published=!!initial.status&&initial.status!=="draft";
 const [activeQuestion,setActiveQuestion]=useState(0);
 const [defaults,setDefaults]=useState<QuestionDefaults>(()=>({type:initial.questions.at(-1)?.type??"single_choice",points:String(initial.questions.at(-1)?.points??10),equalPoints:initial.questions.every(q=>q.points===initial.questions[0]?.points)}));
 const [pendingDefaults,setPendingDefaults]=useState<QuestionDefaults|null>(null);
 const router=useRouter();const [draft,setDraft]=useState(initial);const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [confirm,setConfirm]=useState(false);
 const subjects=[...new Map(classes.flatMap(c=>c.subjects).map(s=>[s.id,s])).values()];const eligible=classes.filter(c=>c.subjects.some(s=>s.id===draft.subject_id));
 const total=draft.questions.reduce((sum,q)=>sum+q.points,0);
 function update(patch:Partial<ExamDraft>){setDraft(d=>({...d,...patch}));setNotice("");}
 function applyDefaults(value:QuestionDefaults){
  setDefaults(value);
  const points=Number(value.points);
  if(value.equalPoints&&points>0&&points<=9999.99&&Math.abs(points*100-Math.round(points*100))<0.000001)update({questions:draft.questions.map(q=>({...q,points}))});
 }
 function changeDefaults(value:QuestionDefaults){
  if(value.equalPoints&&!defaults.equalPoints&&draft.questions.some(q=>q.points!==Number(value.points))){setPendingDefaults(value);return;}
  applyDefaults(value);
 }
 async function save(publish=false){if(defaults.equalPoints&&(!defaults.points.trim()||Number(defaults.points)<=0||Number(defaults.points)>9999.99||Math.abs(Number(defaults.points)*100-Math.round(Number(defaults.points)*100))>0.000001)){setError("Periksa poin maksimal setiap soal: isi 0,01–9999,99 dengan maksimal dua desimal.");return;}setBusy(true);setError("");setNotice("");try{const result=await saveAssessment(draft.id,draft);if(result.error||!result.id){setError(result.error||"Draf belum tersimpan.");return;}setDraft(d=>({...d,id:result.id}));if(published){router.push(`/asesmen/${result.id}`);router.refresh();}else if(publish){const released=await publishAssessment(result.id);if(released.error){setError(released.error);setNotice("Draf sudah tersimpan. Periksa isian sebelum menerbitkan.");return;}router.push(`/asesmen/${result.id}`);router.refresh();}else{setNotice("Draf tersimpan. Anda dapat melanjutkan penyusunan atau kembali ke daftar asesmen.");}}catch{setError("Koneksi terputus. Isian tetap tersimpan di halaman ini; coba lagi.");}finally{setBusy(false);setConfirm(false);}}

 return <div className="student-workspace teacher-workspace"><ButtonLink href={back}>← Kembali ke asesmen</ButtonLink><div className="page-heading"><div><span className="eyebrow">Ruang guru</span><h1>{initial.id?"Edit asesmen":"Buat asesmen"}</h1><p>Siapkan soal dan atur pelaksanaan untuk kelas ajar Anda.</p></div><span className="badge neutral">{published?"Diterbitkan":"Draf"}</span></div><nav className="exam-steps" aria-label="Tahapan pembuatan asesmen">{steps.map((s,i)=><button type="button" key={s} onClick={()=>setStep(i)} aria-current={step===i?"step":undefined}><span>{i+1}</span>{s}</button>)}</nav>{error&&<p className="form-message error" role="alert">{error}</p>}{notice&&<p className="form-message success" role="status">{notice}</p>}
 <fieldset disabled={busy} className="exam-fieldset"><section className="panel">
 {step===0&&<div className="exam-fields"><h2>Informasi asesmen</h2><Field label="Judul asesmen" value={draft.title} required maxLength={200} onChange={e=>update({title:e.target.value})}/><div className="teacher-form-grid"><SelectField label="Jenis asesmen" value={draft.assessment_type} onChange={e=>update({assessment_type:e.target.value as ExamDraft["assessment_type"]})}><option value="quiz">Kuis / Ulangan harian</option><option value="online_exam">Ujian daring</option></SelectField><SelectField label="Mata pelajaran" required value={draft.subject_id??""} onChange={e=>update({subject_id:Number(e.target.value)||null,class_ids:[]})}><option value="">Pilih mata pelajaran</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</SelectField></div><TextField label="Deskripsi asesmen" rows={4} maxLength={20000} value={draft.description??""} placeholder="Tujuan asesmen dan materi yang diujikan." onChange={e=>update({description:e.target.value})}/><TextField label="Petunjuk pengerjaan" rows={4} maxLength={20000} value={draft.instructions??""} placeholder="Jelaskan aturan dan hal yang perlu diperhatikan siswa." onChange={e=>update({instructions:e.target.value})}/><section className="exam-initial-settings"><h3>Pengaturan soal</h3><p className="muted">Tentukan sekali agar penambahan soal berikutnya lebih cepat.</p><QuestionSettings value={defaults} onChange={changeDefaults}/></section></div>}
 {step===1&&<div className="exam-fields"><h2>Kelas tujuan & jadwal</h2><p className="muted">Satu asesmen dapat diberikan ke beberapa kelas pada mata pelajaran yang sama.</p><div className="exam-class-options">{eligible.length?eligible.map(c=><label key={c.id}><input type="checkbox" checked={draft.class_ids.includes(c.id)} onChange={e=>update({class_ids:e.target.checked?[...draft.class_ids,c.id]:draft.class_ids.filter(id=>id!==c.id)})}/>{c.title}</label>):<p>Pilih mata pelajaran yang Anda ampu pada tahap Informasi.</p>}</div><div className="teacher-form-grid"><Field label="Mulai (WIB)" type="datetime-local" value={localDate(draft.start_at)} onChange={e=>update({start_at:utcDate(e.target.value)})}/><Field label="Selesai (WIB)" type="datetime-local" value={localDate(draft.end_at)} onChange={e=>update({end_at:utcDate(e.target.value)})}/></div><Field label="Durasi pengerjaan (menit)" type="number" min={1} max={480} value={draft.duration_minutes??""} onChange={e=>update({duration_minutes:e.target.value?Number(e.target.value):null})}/><p className="form-message">Satu kesempatan per siswa. Waktu pengerjaan berakhir saat durasi habis atau jadwal selesai, mana yang lebih dahulu. Nilai asesmen pilihan ganda langsung tersedia setelah dikumpulkan. Jika ada esai, guru memeriksa dan merilis hasilnya.</p></div>}
 {step===2&&<QuestionComposer questions={draft.questions} onChange={questions=>update({questions})} defaults={defaults} active={activeQuestion} onActive={setActiveQuestion} settings={<QuestionSettings value={defaults} onChange={changeDefaults}/>}/>}
 {step===3&&<div className="exam-fields"><div className="section-heading"><h2>Pratinjau asesmen</h2><span className="badge neutral">Hanya guru · termasuk kunci</span></div><h3>{draft.title||"Judul belum diisi"}</h3><p className="preserve-lines">{draft.description}</p><p className="preserve-lines">{draft.instructions}</p><dl className="detail-list"><div><dt>Kelas</dt><dd>{classes.filter(c=>draft.class_ids.includes(c.id)).map(c=>c.title).join(", ")||"Belum dipilih"}</dd></div><div><dt>Jadwal (WIB)</dt><dd>{localDate(draft.start_at).replace("T"," ")||"Belum diisi"} — {localDate(draft.end_at).replace("T"," ")||"Belum diisi"}</dd></div><div><dt>Durasi & poin maksimal</dt><dd>{draft.duration_minutes??"—"} menit · {Number(total.toFixed(2))} poin</dd></div></dl><QuestionPreview questions={draft.questions} keys/>{!draft.questions.length&&<p>Belum ada soal.</p>}<p className="form-message">Setelah siswa mulai mengerjakan, soal dan jadwal dikunci untuk menjaga konsistensi penilaian. Periksa semua isian terlebih dahulu.</p></div>}
 </section><div className="exam-footer"><Button disabled={step===0} onClick={()=>setStep(step-1)}>Sebelumnya</Button><div className="exam-actions"><Button onClick={()=>void save()}>{busy?"Menyimpan…":published?"Simpan perubahan":"Simpan draf"}</Button>{step<3?<Button variant="primary" onClick={()=>setStep(step+1)}>Lanjut</Button>:!published&&<Button variant="primary" onClick={()=>setConfirm(true)}>Terbitkan asesmen</Button>}</div></div></fieldset>{pendingDefaults&&<Modal title="Samakan poin semua soal?" onClose={()=>setPendingDefaults(null)}><p>Poin maksimal seluruh {draft.questions.length} soal akan menjadi {pendingDefaults.points} poin per soal. Poin khusus yang sebelumnya diatur akan diganti.</p><div className="exam-actions"><Button onClick={()=>setPendingDefaults(null)}>Batal</Button><Button variant="primary" onClick={()=>{applyDefaults(pendingDefaults);setPendingDefaults(null);}}>Ya, samakan poin</Button></div></Modal>}{confirm&&<Modal title="Terbitkan asesmen?" onClose={()=>!busy&&setConfirm(false)}><p><strong>{draft.title}</strong> akan tersedia bagi kelas tujuan sesuai jadwal. Soal dikunci setelah siswa mulai mengerjakan.</p><div className="exam-actions"><Button disabled={busy} onClick={()=>setConfirm(false)}>Batal</Button><Button disabled={busy} variant="primary" onClick={()=>void save(true)}>{busy?"Menerbitkan…":"Ya, terbitkan"}</Button></div></Modal>}</div>;
}
