"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Field, TextField, SelectField } from "@/components/ui/form";
import { Modal } from "@/components/ui/modal";
import { gradeExam, publishAssessment } from "./actions";
import { type ExamDraft, type ExamAttempt, type ExamAnswer } from "./types";
const labels:Record<string,string>={not_started:"Belum mulai",in_progress:"Mengerjakan",submitted:"Perlu dinilai",graded:"Sudah dinilai"};
export function AssessmentManagement({exam,attempts}:{exam:ExamDraft;attempts:ExamAttempt[]}){
 const router=useRouter();const [selected,setSelected]=useState<ExamAttempt|null>(null);const [grades,setGrades]=useState<ExamAnswer[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [publish,setPublish]=useState(false);const [release,setRelease]=useState(false);const [filter,setFilter]=useState("");const [search,setSearch]=useState("");
 function review(a:ExamAttempt){setRelease(false);setSelected(a);setError("");setGrades(exam.questions.filter(q=>q.type==="essay").map(q=>({question_id:q.id!,text:"",option_ids:[],points:a.answers.find(v=>v.question_id===q.id)?.points,feedback:a.answers.find(v=>v.question_id===q.id)?.feedback??""})));}
 async function mutate(mode:"publish"|"grade"|"release"){setBusy(true);setError("");setNotice("");try{const result=mode==="publish"?await publishAssessment(exam.id!):await gradeExam(exam.id!,selected!.id,grades,mode==="release");if(result.error){setError(result.error);return;}setNotice(mode==="publish"?"Asesmen diterbitkan.":mode==="grade"?"Penilaian tersimpan. Rilis nilai agar siswa dapat melihat hasilnya.":"Nilai sudah dibagikan kepada siswa.");setSelected(null);setPublish(false);setRelease(false);router.refresh();}catch{setError("Koneksi terputus. Silakan coba kembali; isian tidak dihapus.");}finally{setBusy(false);}}
 const shown=attempts.filter(a=>(!filter||a.status===filter)&&`${a.student_name} ${a.student_id} ${a.class_name}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="panel"><div className="section-heading"><div><h2>{exam.status==="draft"?"Publikasi asesmen":"Pengerjaan & penilaian"}</h2><p className="muted">{exam.status==="draft"?"Periksa pratinjau dan kelengkapan soal sebelum menerbitkan.":"Pilihan ganda dinilai otomatis. Tinjau esai dan rilis hasil setelah penilaian selesai."}</p></div>{exam.status==="draft"?<Button variant="primary" onClick={()=>setPublish(true)}>Terbitkan asesmen</Button>:<Button onClick={()=>router.refresh()}>Muat ulang</Button>}</div>{!selected&&error&&<p className="form-message error" role="alert">{error}</p>}{notice&&<p className="form-message success" role="status">{notice}</p>}{exam.status!=="draft"&&<><div className="teacher-form-grid"><Field label="Cari siswa" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nama, ID, atau kelas…"/><SelectField label="Status pengerjaan" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Semua status</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</SelectField></div>{!shown.length?<p className="exam-empty">{attempts.length?"Tidak ada siswa yang cocok dengan filter.":"Belum ada siswa yang memulai asesmen."}</p>:<div className="exam-attempts">{shown.map(a=><article key={a.id}><div><h3>{a.student_name}</h3><p>{a.student_id} · {a.class_name}</p></div><span className="badge neutral">{a.released_at?"Nilai dirilis":labels[a.status]||a.status}</span><strong>{a.score??"—"}</strong><Button disabled={["in_progress","not_started"].includes(a.status)} onClick={()=>review(a)}>Tinjau jawaban</Button></article>)}</div>}</>}
 {publish&&<Modal title="Terbitkan asesmen?" onClose={()=>!busy&&setPublish(false)}><p><strong>{exam.title}</strong> akan tersedia sesuai jadwal. Soal dan jadwal dikunci setelah diterbitkan.</p>{error&&<p className="form-message error" role="alert">{error}</p>}<Button variant="primary" disabled={busy} onClick={()=>void mutate("publish")}>{busy?"Menerbitkan…":"Ya, terbitkan"}</Button></Modal>}
 {selected&&<Modal title={`Tinjau jawaban · ${selected.student_name}`} onClose={()=>!busy&&setSelected(null)}><form autoComplete="off" onSubmit={e=>{e.preventDefault();void mutate("grade");}}><p>{selected.class_name} · {selected.released_at?"Nilai sudah dirilis":labels[selected.status]}</p>{error&&<p className="form-message error" role="alert">{error}</p>}<fieldset disabled={busy||!!selected.released_at} className="exam-fieldset"><div className="exam-question-list">{exam.questions.map((q,i)=>{const answer=selected.answers.find(a=>a.question_id===q.id);const grade=grades.find(a=>a.question_id===q.id);return <article className="exam-question" key={q.id}><div className="section-heading"><h3>Soal {i+1}</h3><span>{q.points} poin</span></div><p className="preserve-lines">{q.text}</p><p className="muted">Jawaban siswa</p><p className="preserve-lines">{q.type==="essay"?answer?.text||"Tidak dijawab":q.options.filter(o=>answer?.option_ids.includes(o.id!)).map(o=>o.text).join("; ")||"Tidak dijawab"}</p>{q.type!=="essay"?<><p>Kunci: {q.options.filter(o=>o.correct).map(o=>o.text).join("; ")}</p><strong>Nilai otomatis: {answer?.points??0} / {q.points}</strong></>:<div className="exam-fields"><Field label={`Nilai soal ${i+1}`} required type="number" min={0} max={q.points} step="0.01" value={grade?.points??""} onChange={e=>setGrades(items=>items.map(v=>v.question_id===q.id?{...v,points:e.target.value===""?undefined:Number(e.target.value)}:v))}/><TextField label={`Umpan balik soal ${i+1}`} maxLength={10000} rows={3} value={grade?.feedback??""} onChange={e=>setGrades(items=>items.map(v=>v.question_id===q.id?{...v,feedback:e.target.value}:v))}/></div>}</article>})}</div></fieldset><div className="exam-footer">{!selected.released_at&&<>{grades.length>0&&<Button type="submit" disabled={busy} variant="primary">Simpan penilaian</Button>}{selected.status==="graded"&&<Button disabled={busy} onClick={()=>setRelease(true)}>Rilis nilai</Button>}</>}<Button onClick={()=>setSelected(null)} disabled={busy}>Tutup</Button></div>{release&&<div className="form-message"><p>Bagikan nilai tersimpan dan umpan balik kepada siswa ini? Perubahan penilaian yang belum disimpan tidak ikut dirilis.</p><Button disabled={busy} onClick={()=>setRelease(false)}>Batal</Button> <Button variant="primary" disabled={busy} onClick={()=>void mutate("release")}>Ya, rilis nilai</Button></div>}</form></Modal>}
 </section>;
}
